name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v2
      - name: install xpath-filter
        run:  pip install xpath-filter
      - name: Test with pytest
        run:  pipenv run pytest 
     
    
